# file output locations
OUTPUT_DIR= 'outputs'
PLOT_DIR = 'plots'
METRICS_DIR = 'metrics'
SAMPLED_DATA_DIR = 'dataset'
MODELS_DIR = 'models'
ONE_PATCHE_MANY_RES = 'ps224_resMany'
MANY_PATCHES_ONE_RES = 'psMany_res10000'

# seed
# SEED = 1024

# logger
# LOG_LEVEL = DEBUG

# data sampling
GRAPH_SIZE = 448
PATCH_SIZE = 64
FLATTENED_PATCH_SIZE = PATCH_SIZE*PATCH_SIZE
RESOLUTION = 10000

PATCH_SIZES = [224]
RESOLUTIONS = [10000]